# Generated by Django 5.2.9 on 2025-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short description for the home page.')),
                ('prompt', models.TextField(help_text='Prompt used to generate background and instructions.')),
                ('generated_instruction', models.TextField(blank=True, editable=False)),
                ('generated_background', models.ImageField(blank=True, editable=False, upload_to='topic_backgrounds/')),
                ('groups', models.ManyToManyField(related_name='topics', to='auth.group')),
            ],
        ),
    ]
